name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install distlib==0.3.8
        pip install filelock==3.13.1
        pip install packaging==23.2
        pip install platformdirs==4.2.0
        pip install poetry
        poetry config virtualenvs.create false
        poetry install
    - name: Run Migrations
      run: |
        python src/manage.py makemigrations catalog
        python src/manage.py makemigrations users
        python src/manage.py migrate
    - name: Run Tests
      run: |
        python src/manage.py test catalog
        python src/manage.py test users
